@startuml packages_VampireSurvivors
set namespaceSeparator none
package "VampireSurvivors" as VampireSurvivors {
}
package "VampireSurvivors.business" as VampireSurvivors.business {
}
package "VampireSurvivors.business.entities" as VampireSurvivors.business.entities {
}
package "VampireSurvivors.business.entities.bullet" as VampireSurvivors.business.entities.bullet {
}
package "VampireSurvivors.business.entities.collectibles" as VampireSurvivors.business.entities.collectibles {
}
package "VampireSurvivors.business.entities.collectibles.chest" as VampireSurvivors.business.entities.collectibles.chest {
}
package "VampireSurvivors.business.entities.collectibles.collectible" as VampireSurvivors.business.entities.collectibles.collectible {
}
package "VampireSurvivors.business.entities.collectibles.experience_gem" as VampireSurvivors.business.entities.collectibles.experience_gem {
}
package "VampireSurvivors.business.entities.collectibles.healing_gem" as VampireSurvivors.business.entities.collectibles.healing_gem {
}
package "VampireSurvivors.business.entities.entity" as VampireSurvivors.business.entities.entity {
}
package "VampireSurvivors.business.entities.interfaces" as VampireSurvivors.business.entities.interfaces {
}
package "VampireSurvivors.business.entities.monster_factory" as VampireSurvivors.business.entities.monster_factory {
}
package "VampireSurvivors.business.entities.monsters" as VampireSurvivors.business.entities.monsters {
}
package "VampireSurvivors.business.entities.monsters.boss" as VampireSurvivors.business.entities.monsters.boss {
}
package "VampireSurvivors.business.entities.monsters.default_monster" as VampireSurvivors.business.entities.monsters.default_monster {
}
package "VampireSurvivors.business.entities.monsters.monster" as VampireSurvivors.business.entities.monsters.monster {
}
package "VampireSurvivors.business.entities.monsters.red_ghost" as VampireSurvivors.business.entities.monsters.red_ghost {
}
package "VampireSurvivors.business.entities.player" as VampireSurvivors.business.entities.player {
}
package "VampireSurvivors.business.exceptions" as VampireSurvivors.business.exceptions {
}
package "VampireSurvivors.business.handlers" as VampireSurvivors.business.handlers {
}
package "VampireSurvivors.business.handlers.collision_handler" as VampireSurvivors.business.handlers.collision_handler {
}
package "VampireSurvivors.business.handlers.cooldown_handler" as VampireSurvivors.business.handlers.cooldown_handler {
}
package "VampireSurvivors.business.handlers.data_handler" as VampireSurvivors.business.handlers.data_handler {
}
package "VampireSurvivors.business.handlers.death_handler" as VampireSurvivors.business.handlers.death_handler {
}
package "VampireSurvivors.business.handlers.interfaces" as VampireSurvivors.business.handlers.interfaces {
}
package "VampireSurvivors.business.handlers.item_data_handler" as VampireSurvivors.business.handlers.item_data_handler {
}
package "VampireSurvivors.business.handlers.position_handler" as VampireSurvivors.business.handlers.position_handler {
}
package "VampireSurvivors.business.progression" as VampireSurvivors.business.progression {
}
package "VampireSurvivors.business.progression.interfaces" as VampireSurvivors.business.progression.interfaces {
}
package "VampireSurvivors.business.progression.inventory" as VampireSurvivors.business.progression.inventory {
}
package "VampireSurvivors.business.progression.item" as VampireSurvivors.business.progression.item {
}
package "VampireSurvivors.business.progression.item_factory" as VampireSurvivors.business.progression.item_factory {
}
package "VampireSurvivors.business.progression.perk" as VampireSurvivors.business.progression.perk {
}
package "VampireSurvivors.business.progression.perk_factory" as VampireSurvivors.business.progression.perk_factory {
}
package "VampireSurvivors.business.progression.player_stats" as VampireSurvivors.business.progression.player_stats {
}
package "VampireSurvivors.business.progression.upgrade" as VampireSurvivors.business.progression.upgrade {
}
package "VampireSurvivors.business.weapons" as VampireSurvivors.business.weapons {
}
package "VampireSurvivors.business.weapons.attack_whip" as VampireSurvivors.business.weapons.attack_whip {
}
package "VampireSurvivors.business.weapons.gun" as VampireSurvivors.business.weapons.gun {
}
package "VampireSurvivors.business.weapons.hitbox" as VampireSurvivors.business.weapons.hitbox {
}
package "VampireSurvivors.business.weapons.interfaces" as VampireSurvivors.business.weapons.interfaces {
}
package "VampireSurvivors.business.weapons.weapon" as VampireSurvivors.business.weapons.weapon {
}
package "VampireSurvivors.business.weapons.weapon_factory" as VampireSurvivors.business.weapons.weapon_factory {
}
package "VampireSurvivors.business.weapons.weapon_stats" as VampireSurvivors.business.weapons.weapon_stats {
}
package "VampireSurvivors.business.weapons.whip" as VampireSurvivors.business.weapons.whip {
}
package "VampireSurvivors.business.world" as VampireSurvivors.business.world {
}
package "VampireSurvivors.business.world.chest_spawner" as VampireSurvivors.business.world.chest_spawner {
}
package "VampireSurvivors.business.world.clock" as VampireSurvivors.business.world.clock {
}
package "VampireSurvivors.business.world.collectible_factory" as VampireSurvivors.business.world.collectible_factory {
}
package "VampireSurvivors.business.world.game_world" as VampireSurvivors.business.world.game_world {
}
package "VampireSurvivors.business.world.interfaces" as VampireSurvivors.business.world.interfaces {
}
package "VampireSurvivors.business.world.monster_spawner" as VampireSurvivors.business.world.monster_spawner {
}
package "VampireSurvivors.business.world.tile_map" as VampireSurvivors.business.world.tile_map {
}
package "VampireSurvivors.game" as VampireSurvivors.game {
}
package "VampireSurvivors.persistance" as VampireSurvivors.persistance {
}
package "VampireSurvivors.persistance.dao" as VampireSurvivors.persistance.dao {
}
package "VampireSurvivors.persistance.dao.json_attacks" as VampireSurvivors.persistance.dao.json_attacks {
}
package "VampireSurvivors.persistance.dao.json_collectibles" as VampireSurvivors.persistance.dao.json_collectibles {
}
package "VampireSurvivors.persistance.dao.json_inventory" as VampireSurvivors.persistance.dao.json_inventory {
}
package "VampireSurvivors.persistance.dao.json_monster" as VampireSurvivors.persistance.dao.json_monster {
}
package "VampireSurvivors.persistance.dao.json_player" as VampireSurvivors.persistance.dao.json_player {
}
package "VampireSurvivors.persistance.interfaces" as VampireSurvivors.persistance.interfaces {
}
package "VampireSurvivors.persistance.json_helpers" as VampireSurvivors.persistance.json_helpers {
}
package "VampireSurvivors.presentation" as VampireSurvivors.presentation {
}
package "VampireSurvivors.presentation.camera" as VampireSurvivors.presentation.camera {
}
package "VampireSurvivors.presentation.display" as VampireSurvivors.presentation.display {
}
package "VampireSurvivors.presentation.exceptions" as VampireSurvivors.presentation.exceptions {
}
package "VampireSurvivors.presentation.handlers" as VampireSurvivors.presentation.handlers {
}
package "VampireSurvivors.presentation.handlers.userinterface_handler" as VampireSurvivors.presentation.handlers.userinterface_handler {
}
package "VampireSurvivors.presentation.input_handler" as VampireSurvivors.presentation.input_handler {
}
package "VampireSurvivors.presentation.interfaces" as VampireSurvivors.presentation.interfaces {
}
package "VampireSurvivors.presentation.menus" as VampireSurvivors.presentation.menus {
}
package "VampireSurvivors.presentation.menus.game_over" as VampireSurvivors.presentation.menus.game_over {
}
package "VampireSurvivors.presentation.menus.hud" as VampireSurvivors.presentation.menus.hud {
}
package "VampireSurvivors.presentation.menus.main_menu" as VampireSurvivors.presentation.menus.main_menu {
}
package "VampireSurvivors.presentation.menus.menu" as VampireSurvivors.presentation.menus.menu {
}
package "VampireSurvivors.presentation.menus.pause" as VampireSurvivors.presentation.menus.pause {
}
package "VampireSurvivors.presentation.menus.upgrade_menu" as VampireSurvivors.presentation.menus.upgrade_menu {
}
package "VampireSurvivors.presentation.sprite" as VampireSurvivors.presentation.sprite {
}
package "VampireSurvivors.presentation.tileset" as VampireSurvivors.presentation.tileset {
}
package "VampireSurvivors.presentation.userinterface" as VampireSurvivors.presentation.userinterface {
}
package "VampireSurvivors.presentation.userinterface.button" as VampireSurvivors.presentation.userinterface.button {
}
package "VampireSurvivors.presentation.userinterface.dynamic_text" as VampireSurvivors.presentation.userinterface.dynamic_text {
}
package "VampireSurvivors.presentation.userinterface.image_component" as VampireSurvivors.presentation.userinterface.image_component {
}
package "VampireSurvivors.presentation.userinterface.text" as VampireSurvivors.presentation.userinterface.text {
}
package "VampireSurvivors.presentation.userinterface.uicomponent" as VampireSurvivors.presentation.userinterface.uicomponent {
}
package "VampireSurvivors.runner" as VampireSurvivors.runner {
}
package "VampireSurvivors.settings" as VampireSurvivors.settings {
}
package "VampireSurvivors.tests" as VampireSurvivors.tests {
}
package "VampireSurvivors.tests.test_bullet" as VampireSurvivors.tests.test_bullet {
}
package "VampireSurvivors.tests.test_itemdata" as VampireSurvivors.tests.test_itemdata {
}
package "VampireSurvivors.tests.test_monster" as VampireSurvivors.tests.test_monster {
}
package "VampireSurvivors.tests.test_weaponupgrades" as VampireSurvivors.tests.test_weaponupgrades {
}
package "VampireSurvivors.tests.world_mock" as VampireSurvivors.tests.world_mock {
}
VampireSurvivors.game --> VampireSurvivors.business.exceptions
VampireSurvivors.game --> VampireSurvivors.business.handlers.collision_handler
VampireSurvivors.game --> VampireSurvivors.business.handlers.death_handler
VampireSurvivors.game --> VampireSurvivors.business.handlers.item_data_handler
VampireSurvivors.game --> VampireSurvivors.business.world.interfaces
VampireSurvivors.game --> VampireSurvivors.persistance.dao.json_collectibles
VampireSurvivors.game --> VampireSurvivors.persistance.dao.json_inventory
VampireSurvivors.game --> VampireSurvivors.persistance.dao.json_monster
VampireSurvivors.game --> VampireSurvivors.persistance.dao.json_player
VampireSurvivors.game --> VampireSurvivors.persistance.json_helpers
VampireSurvivors.game --> VampireSurvivors.presentation.exceptions
VampireSurvivors.game --> VampireSurvivors.presentation.interfaces
VampireSurvivors.game --> VampireSurvivors.settings
VampireSurvivors.runner --> VampireSurvivors.business.world.chest_spawner
VampireSurvivors.runner --> VampireSurvivors.business.world.game_world
VampireSurvivors.runner --> VampireSurvivors.business.world.monster_spawner
VampireSurvivors.runner --> VampireSurvivors.business.world.tile_map
VampireSurvivors.runner --> VampireSurvivors.game
VampireSurvivors.runner --> VampireSurvivors.persistance.json_helpers
VampireSurvivors.runner --> VampireSurvivors.presentation.display
VampireSurvivors.runner --> VampireSurvivors.presentation.exceptions
VampireSurvivors.runner --> VampireSurvivors.presentation.input_handler
VampireSurvivors.runner --> VampireSurvivors.settings
@enduml
